const products = [
    {
      name: "Кульки-цифри на День Народження",
      description: "Великі надувні кульки у формі цифр для святкування особливого дня. Висота: 100 см.",
      price: 399.99,
      image: "https://content1.rozetka.com.ua/goods/images/big/426668327.jpg",
      cloudinaryId: "balloon-products/number-balloons",
      category: "Святкові набори",
      stock: 30,
    },
    {
      name: "Повітряні кульки 'Єдиноріг'",
      description: "Тематичні кульки з зображенням єдинорогів для дитячих вечірок. У наборі 10 штук.",
      price: 199.99,
      image: "https://images.prom.ua/4223786003_w0_h430_fontan-z-kulok.jpg",
      cloudinaryId: "balloon-products/unicorn-balloons",
      category: "Тематичні кульки",
      stock: 45,
    },
    {
      name: "Металеві кульки 'Хром'",
      description: "Елегантні кульки з ефектом хромованого металу. Ідеальні для весіль та корпоративних заходів.",
      price: 499.99,
      image: "https://cdn.27.ua/799/72/b5/6976181_1.jpeg",
      cloudinaryId: "balloon-products/chrome-balloons",
      category: "Святкові набори",
      stock: 25,
    },
    {
      name: "Фольговані кульки 'Серце'",
      description: "Романтичні фольговані кульки у формі серця. Ідеально для Дня Закоханих або річниці.",
      price: 159.99,
      image: "https://makemehappy.com.ua/content/images/5/379x390l80mc0/65635303448418.webp",
      cloudinaryId: "balloon-products/heart-balloons",
      category: "Фольговані кульки",
      stock: 40,
    },
    {
      name: "Геліві кульки 'Прозорі з конфетті'",
      description: "Стильні прозорі кульки, заповнені різнокольоровим конфетті. Наповнені гелієм для тривалого польоту.",
      price: 249.99,
      image: "https://makemehappy.com.ua/content/images/34/825x1100l80mc0/11331440926917.webp",
      cloudinaryId: "balloon-products/confetti-balloons",
      category: "Геліві кульки",
      stock: 35,
    },
    {
      name: "Кулька-ходячка 'Динозавр'",
      description: "Велика фольгована кулька у формі динозавра, яка тримається на підлозі. Висота: 120 см.",
      price: 599.99,
      image: "https://cool-sharkiev.com.ua/wp-content/uploads/2023/01/1-1540-350x350.jpg",
      cloudinaryId: "balloon-products/dino-balloon",
      category: "Фольговані кульки",
      stock: 15,
    },
    {
      name: "Світлові LED-кульки",
      description: "Інноваційні кульки з вбудованими LED-вогниками для вечірок у темряві. Працюють до 24 годин.",
      price: 349.99,
      image: "https://content2.rozetka.com.ua/goods/images/big/529979201.jpg",
      cloudinaryId: "balloon-products/led-balloons",
      category: "Святкові набори",
      stock: 20,
    },
    {
      name: "Повітряні кульки 'З Днем Народження'",
      description: "Готовий набір кульок з написом 'З Днем Народження' українською мовою. 15 кульок у наборі.",
      price: 279.99,
      image: "https://makemehappy.com.ua/content/images/26/488x390l80mc0/98170673957212.webp",
      cloudinaryId: "balloon-products/birthday-balloons-ukr",
      category: "Святкові набори",
      stock: 50,
    },
    {
      name: "Гігантська кулька-сюрприз",
      description: "Величезна кулька діаметром 90 см, яка може бути заповнена маленькими кульками або подарунками.",
      price: 899.99,
      image: "https://i.prazdnik-shop.com.ua/25672-large_default/shar-syurpriz-1.webp",
      cloudinaryId: "balloon-products/giant-surprise-balloon",
      category: "Геліві кульки",
      stock: 10,
    },
    {
      name: "Набір кульок 'Космос'",
      description: "Тематичний набір кульок із зображенням планет, зірок і космічних кораблів. 12 кульок у наборі.",
      price: 229.99,
      image: "https://content.rozetka.com.ua/goods/images/big/311298929.jpg",
      cloudinaryId: "balloon-products/space-balloons",
      category: "Тематичні кульки",
      stock: 30,
    },
    {
      name: "Кульки 'Прапор України'",
      description: "Патріотичний набір кульок у кольорах українського прапора: жовтих і блакитних. 20 кульок у наборі.",
      price: 199.99,
      image: "https://4party.ua/upload/resize_cache/iblock/33f/360_390_1/vozdushnyy_shar_ukraina_prezhde_vsego_30_sm.jpg.webp",
      cloudinaryId: "balloon-products/ukrainian-flag-balloons",
      category: "Тематичні кульки",
      stock: 100,
    },
    {
      name: 'Аеростат "Повітряна куля"',
      description: "Декоративна модель класичного аеростата у вигляді повітряної кулі. Висота: 50 см.",
      price: 1299.99,
      image: "https://paradise.kiev.ua/image/cache/product_images/fotozona/product-_b6918f55d7040785c01dc95d43b6f86d-ipthumb565xprop-1200x1200.jpg",
      cloudinaryId: "balloon-products/hot-air-balloon-model",
      category: "Аксесуари",
      stock: 8,
    },
    {
      name: "Професійний комплект для моделювання кульок",
      description: "Повний набір для створення фігур з повітряних кульок. Включає насос, 100 кульок для моделювання та інструкцію.",
      price: 1499.99,
      image: "https://funfan.ua/img/cms/1022221730.jpg",
      cloudinaryId: "balloon-products/balloon-modelling-kit",
      category: "Аксесуари",
      stock: 15,
    },
    {
      name: "Кульки на День Святого Валентина",
      description: "Романтичний набір кульок для Дня Закоханих з малюнками сердець та нарисами кохання. 15 кульок у наборі.",
      price: 199.99,
      image: "https://ukrasharik.com/images/virtuemart/product/5303-0351.jpg",
      cloudinaryId: "balloon-products/valentines-balloons",
      category: "Тематичні кульки",
      stock: 35,
    },
    {
      name: "Дитячі кульки 'Мультфільми'",
      description: "Набір кульок із зображеннями улюблених персонажів з мультфільмів. Ідеально для дитячих вечірок.",
      price: 249.99,
      image: "https://4party.ua/upload/iblock/1cc/product_detail_3202_2977_m1.png.webp",
      cloudinaryId: "balloon-products/cartoon-balloons",
      category: "Тематичні кульки",
      stock: 42,
    },
    {
      name: "Електричний насос для кульок",
      description: "Професійний електричний насос для швидкого надування повітряних кульок. Компактний та потужний.",
      price: 899.99,
      image: "https://perfectparty.in.ua/optimize/img/p/7/3/8/4/7384-large_default.jpg.webp",
      cloudinaryId: "balloon-products/electric-pump",
      category: "Аксесуари",
      stock: 10,
    },
    {
      name: "Кульки з індивідуальним написом",
      description: "Можливість замовити кульки з власним текстом, логотипом або малюнком. Мінімальне замовлення: 10 штук.",
      price: 449.99,
      image: "https://sakrial.com.ua/content/uploads/images/vozdushnye-shariki-s-individualnoj-nadpisju%281%29.jpg",
      cloudinaryId: "balloon-products/custom-text-balloons",
      category: "Святкові набори",
      stock: 100,
    },
    {
      name: "Фольговані цифри 'Золото'",
      description: "Золоті цифри з фольги висотою 102 см. Продаються поштучно для складання дати або віку.",
      price: 129.99,
      image: "https://pvdecor.com.ua/content/images/10/870x546l80mc0/kulia-folhovana-zoloto-tsyfra-8-v-upakovtsi-84253917400971.png",
      cloudinaryId: "balloon-products/gold-number-balloons",
      category: "Фольговані кульки",
      stock: 80,
    }
  ];
  
  export default products;